import os
import pandas as pd
from pathlib import Path
from PIL import Image

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

# ==============================================================================
# 1. PYTORCH DATASET CLASS (Production Ready)
# ==============================================================================
class MedicalDataset(Dataset):
    """
    Production-Quality PyTorch Dataset that strictly reads from our Immutable CSV Splits.
    """
    def __init__(self, split_csv_path: str, images_dir: str, transform=None):
        self.images_dir = Path(images_dir)
        self.transform = transform
        
        if not os.path.exists(split_csv_path):
            raise FileNotFoundError(f"Split CSV not found at: {split_csv_path}")
            
        # Read the static CSV split generated by our DatasetProcessor
        self.data = pd.read_csv(split_csv_path)
        
    def __len__(self):
        return len(self.data)
        
    def __getitem__(self, idx):
        # 1. Get the filename and class_id
        row = self.data.iloc[idx]
        filename = row['filename']
        label = row['class_id']
        
        # 2. Construct absolute path
        img_path = self.images_dir / filename
        
        # 3. Open image via PIL (Convert to RGB for DenseNet)
        image = Image.open(img_path).convert('RGB')
        
        # 4. Apply transformations
        if self.transform:
            image = self.transform(image)
            
        return image, torch.tensor(label, dtype=torch.long)

# ==============================================================================
# 2. DATALOADER GENERATOR
# ==============================================================================
def get_dataloaders(splits_dir: str, images_dir: str, batch_size: int = 32):
    """
    Creates the Train and Validation DataLoaders by reading the structured splits.
    """
    
    # --- Data Augmentation for Training ---
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),       
        transforms.RandomHorizontalFlip(),   
        transforms.RandomRotation(10),       
        transforms.ToTensor(),               
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) 
    ])
    
    # --- Transformations for Validation ---
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    # Paths to the CSVs
    train_csv = os.path.join(splits_dir, 'train.csv')
    val_csv = os.path.join(splits_dir, 'validation.csv')
    
    # Initialize the datasets
    train_ds = MedicalDataset(train_csv, images_dir, transform=train_transform)
    val_ds = MedicalDataset(val_csv, images_dir, transform=val_transform)
    
    # Create the DataLoaders
    # Note: num_workers=4 speeds up dataloading
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=True)
    
    return train_loader, val_loader
